# Generated by Django 5.2 on 2025-04-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_userclubinteraction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('STEM', 'STEM'), ('SPORTS', 'Sports'), ('CULTURE', 'Culture')], default='CULTURE', max_length=20),
        ),
    ]
