# Generated by Django 5.2 on 2025-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='club',
            name='meeting_dates',
        ),
        migrations.RemoveField(
            model_name='club',
            name='meeting_times',
        ),
        migrations.AddField(
            model_name='club',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='meeting_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='banner',
            field=models.ImageField(blank=True, default='club_banners/default_banner.jpg', null=True, upload_to='club_banners/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('STEM', 'STEM'), ('SPORTS', 'Sports'), ('CULTURE', 'Culture')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, default='club_logos/default_logo.jpg', null=True, upload_to='club_logos/'),
        ),
    ]
