# Generated by Django 5.2 on 2025-04-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_club_benefits_remove_club_meeting_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('STEM', 'STEM'), ('SPORTS', 'Sports'), ('CULTURE', 'Culture'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
