# Generated by Django 5.2 on 2025-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_club_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Social Sorority', 'Social Sorority'), ('Social Fraternity', 'Social Fraternity'), ('Academic Major Related', 'Academic Major Related'), ('Religious Based', 'Religious Based'), ('Service & Support', 'Service & Support'), ('Honor Society', 'Honor Society'), ('Greek Auxiliary Group', 'Greek Auxiliary Group'), ('Leadership', 'Leadership'), ('Political', 'Political'), ('Recreational', 'Recreational'), ('Imperial Valley Campus', 'Imperial Valley Campus'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
