# Generated by Django 5.2 on 2025-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_club_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
