# Generated by Django 5.2 on 2025-04-30 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newsubmission_bio_newsubmission_profile_picture_and_more'),
        ('clubs', '0007_club_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('preferred_time', models.CharField(max_length=100)),
                ('avatar_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='accounts.newsubmission')),
            ],
            options={
                'unique_together': {('user', 'liked_user_id')},
            },
        ),
    ]
