# Generated by Django 5.2 on 2025-04-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('verification_code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=100)),
                ('sports', models.CharField(max_length=100)),
            ],
        ),
    ]
