# Generated by Django 5.2 on 2025-04-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsubmission',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsubmission',
            name='race',
            field=models.CharField(choices=[('', 'Select Race/Ethnicity'), ('asian', 'Asian'), ('black', 'Black or African American'), ('hispanic', 'Hispanic or Latino'), ('white', 'White'), ('native_american', 'Native American'), ('pacific_islander', 'Pacific Islander'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsubmission',
            name='sports',
            field=models.CharField(choices=[('', 'Select Interest'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default='', max_length=100),
        ),
    ]
